spring:
  application:
    name: dispatcher-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS}  # Changed to environment variable
          required-acks: all
          replication-factor: 3
      bindings:
        appointmentCreated-in-0:  # Added consumer binding
          destination: appointment.created
          contentType: application/json
          group: ${spring.application.name}
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 1000
            backOffMaxInterval: 10000
            backOffMultiplier: 2.0
      function:
        definition: handleAppointment  # Added function definition
    kubernetes:  # Added Kubernetes config
      enabled: true
      reload:
        enabled: true
        mode: polling
        period: 15000
    loadbalancer:
      request:
        timeout:
          connect: 2500
          read: 2500
      fail-fast: false
      retry:
        max-attempts: 8
        initial-interval: 1500
        max-interval: 3000
        multiplier: 1.5


server:
  port: 9030
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

management:
  server:
    port: 8030
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,metrics,prometheus,refresh,info,env,mappings,beans
  export:
    prometheus:
      enabled: true
      step: 30s
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    metrics:
      tags:
        application: ${spring.application.name}
logging:
  pattern:
    console: "%clr(${spring.application.name} %d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: INFO
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.cloud.stream.binder.kafka: DEBUG
    org.springframework.security: INFO
    org.springframework.cloud: DEBUG                     # Spring Cloud components
    org.springframework.cloud.kubernetes: DEBUG          # Kubernetes integration
    org.springframework.web.client.RestTemplate: DEBUG   # Inter-service REST calls
    org.springframework.web.reactive: DEBUG              # WebClient calls
    org.springframework.boot.actuate: DEBUG             # Actuator endpoints
    org.springframework.cloud.loadbalancer: DEBUG       # Load balancing
    org.springframework.retry: DEBUG                     # Retry mechanisms
    org.springframework.cache: DEBUG                     # Caching operations
    io.micrometer: DEBUG                                # Metrics collection
    org.springframework.cloud.circuit.breaker: DEBUG
    com.pam.dispatcherservice: DEBUG
    org.springframework.boot.availability: DEBUG
  file:
    name: logs/dispatcher-service.log
    max-size: 10MB
    max-history: 7
    total-size-cap: 100MB
