spring:
  application:
    name: dispatcher-service
  cloud:
    kubernetes:
      config:
        enabled: true
        name: dispatcher-service
        namespace: default
      reload:
        enabled: true
  devtools:
    livereload:
      port: 35730
