apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-service
  labels:
    app: provider-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider-service
  template:
    metadata:
      labels:
        app: provider-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8010"
    spec:
      serviceAccountName: provider-service
      containers:
        - name: provider-service
          image: provider-service
          imagePullPolicy: Never
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/workspace/configmap/application.yml
            - name: PROVIDER_SERVICE_HOSTNAME
              value: "providers-postgres"
            - name: PROVIDER_SERVICE_DB
              value: "providers"
            - name: PROVIDER_SERVICE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: providers-db-credentials
                  key: username
            - name: PROVIDER_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: provider-db-credentials
                  key: password
          volumeMounts:
            - name: provider-config-volume
              mountPath: /workspace/configmap
      volumes:
        - name: patient-config-volume
          configMap:
            name: provider-service
