apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  labels:
    app: appointment-service
spec:
  type: ClusterIP
  selector:
    app: appointment-service
  ports:
    - name: app
      protocol: TCP
      port: 9020
      targetPort: 9020
    - name: management
      protocol: TCP
      port: 8020
      targetPort: 8020
    - name: debug
      protocol: TCP
      port: 5005
      targetPort: 5005
