apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  labels:
    app: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8010"
    spec:
      serviceAccountName: patient-service
      containers:
        - name: patient-service
          image: patient-service
          imagePullPolicy: Never
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/workspace/configmap/application.yml
            - name: PATIENT_SERVICE_HOSTNAME
              value: "patients-postgres"
            - name: PATIENT_SERVICE_DB
              value: "patients"
            - name: PATIENT_SERVICE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: patient-db-credentials
                  key: username
            - name: PATIENT_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: patient-db-credentials
                  key: password
          volumeMounts:
            - name: patient-config-volume
              mountPath: /workspace/configmap
      volumes:
        - name: patient-config-volume
          configMap:
            name: patient-service
