apiVersion: v1
kind: Service
metadata:
  name: patient-service
  labels:
    app: patient-service
spec:
  type: ClusterIP
  selector:
    app: patient-service
  ports:
    - name: app
      protocol: TCP
      port: 9010
      targetPort: 9010
    - name: management
      protocol: TCP
      port: 8010
      targetPort: 8010
    - name: debug
      protocol: TCP
      port: 5005
      targetPort: 5005
