services:
  patient-service:
    build:
      context: ../patient-service
      dockerfile: Dockerfile
    container_name: patient-service
    ports:
      - "9010:9010"
      - "8010:8010"
      - "5005:5005"
    environment:
        JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
#    env_file:
#      - .env
    networks:
      - general-hospital-network
networks:
  general-hospital-network:
    name: general-hospital-network