global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'patient-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'patient-service:8010' ]

  - job_name: 'appointment-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'appointment-service:8020' ]

  - job_name: 'dispatcher-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'dispatcher-service:8030' ]

  - job_name: 'provider-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'provider-service:8040' ]