global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'patient-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'patient-service:9010' ]

