spring:
  application:
    name: patient-service
  cloud:
    kubernetes:
      config:
        enabled: false
        name: patient-service
        namespace: default
      reload:
        enabled: true
  devtools:
    livereload:
      port: 35730
